### PR TITLE
State in description

### PR DESCRIPTION
**Pull request by lstocchi**
@odockal here the server state is in the description.

### CODE REVIEW

**Comment by robstryker** [comment]
got a screenshot to show if / how this affects UI?

**Comment by lstocchi** [comment]
The change is minimal
image

I just created this PR because Ondrej is creating ui test and he wants to see if he is able to retrieve nodes this way. In the current implementation the label always changes and he is not able to make any test. BTW he is also testing with the other PR so maybe this won't be used.

**Comment by odockal** [comment]
@lstocchi  Can you please also update the test? Many are failing.

**Comment by odockal** [comment]
@lstocchi Nice! Thanks.

**Comment by robstryker** [comment]
+1

**Pull request merged**
