### PR TITLE
changed way simple info quickpick are shown (#75)

### LINKED ISSUE #75: Make steps without input but informations to "continue" more user-friendly
See https://github.com/redhat-developer/vscode-server-connector/pull/271

### PR DESCRIPTION
**Pull request by lstocchi**
it fixes #75 

@odockal  after trying different stuff this seems to me the most complete solution. Let me know what you think.

Basically when a info quickpick is shown, the "Continue..." option is always displayed and the user is prevented from typing anything in the text field. If the user start typing, the content inserted by him/her is cancelled and an information message box is displayed with a message 'Select Continue... to go to the next step'.

### CODE REVIEW

**Comment by robstryker** [comment]
Code review looks good to me.  Will await @odockal feedback to know if he feels it flows properly ;)

**Comment by odockal** [comment]
@lstocchi @robstryker Guys, sorry for missing this.

I tried the patch and it looks good.
Steps:
Start RSP -> Create New Server -> Download -> EAP 7.2.0 -> ...
Here I got an input box with information to provide my credentials, typing does "nothing", letters are erased, notification appears, and so it is pretty clear to "continue...".
Until here it is nice.
But there are/is an issue(s)
when I get to signing license where input box contains "License URL:....lgpl-2.1.txt" and offering Continue..., I cannot click on it. I can just press enter. When I do so, (pressing enter) I go to "Do you agree to license?" and notification appears from previous input I guess. 

Seems like there is a bug in flow, right?

**Comment by lstocchi** [comment]
@odockal you were right, there was a problem in that step. The message returned by the server contained a new line which got removed by the quickpick by default and so it kept triggering the onDidChangeValue event by not allowing doing anything. It was like .... message returned from server is "msg: /n xxxx" while in quickpick we have "msg: xxx" so there is a change -> trigger event lol. 
I cleaned up the prompt message because new line are not displayed in a simple quickpick. It should work now :+1:

**Comment by odockal** [comment]
@lstocchi Yeah, it works now. So, +1 from me.

**Pull request merged**
