### PR TITLE
Fixes #183 - update telemetry dep

### LINKED ISSUE #183: Remove dependency to vscode-commons
https://github.com/redhat-developer/vscode-rsp-ui/blob/61f87295b2b12ce345eeaf0aaed72a1d00422a49/package.json#L19

See https://github.com/redhat-developer/vscode-redhat-telemetry#how-to-use-this-library and [YAML](https://github.com/redhat-developer/vscode-yaml/pull/528/files) integration as an example

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by robstryker** [comment]
Builds successfully locally, no idea whats wrong here on build system. :|

**Comment by jeffmaury** [comment]
Check the vscode-project-initializer PR I had to update vscode-extension-tester

**Comment by robstryker** [comment]
> Check the vscode-project-initializer PR I had to update vscode-extension-tester

thanks for the update. Missed that line somehow. Fixing.

**Comment by fbricon** [comment]
@robstryker you missed the API changes 
- https://github.com/redhat-developer/vscode-redhat-telemetry#add-the-below-code-to-your-extensionts  
- https://github.com/redhat-developer/vscode-yaml/pull/528/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R86

**Pull request merged**
